<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
    <AssemblyName>imrdy</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\imrdy.ico" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Imrdy.Integration.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Svg" Version="3.4.7" />
    <PackageReference Include="System.Threading.AccessControl" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imrdy.Core\Imrdy.Core.csproj" />
  </ItemGroup>


</Project>
