<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <AssemblyName>imrdy</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imrdy.Core\Imrdy.Core.csproj" />
  </ItemGroup>

</Project>
