<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="imrdy" />
    <InternalsVisibleTo Include="Imrdy.Linux" />
    <InternalsVisibleTo Include="Imrdy.Core.Tests" />
    <InternalsVisibleTo Include="Imrdy.Integration.Tests" />
    <InternalsVisibleTo Include="Imrdy.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.3.25171.5" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0" />
  </ItemGroup>

</Project>
